name: GitHub Readme YouTube Cards
on:
  schedule:
    # Runs every hour, on the hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        with:
          channel_id: UCcmepIMIaVSYErNDbzjRbNQ
          comment_tag_name: YOUTUBE-CARDS
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
          show_duration: true
      - run: echo "YOUTUBE_API_KEY is set"
  if: ${{ secrets.YOUTUBE_API_KEY != '' }}


# put your you tube here learn it probably wont be that hard hopefully
# also make sure this is private becuase you api is gonna be expose